<?php

namespace App\Service;

use App\Repository\CustomerRepository;
use Psr\Log\LoggerInterface;

class MonthlyDebtGenerator
{
    public function __construct(
        private readonly CustomerRepository $customerRepository,
        private readonly ?LoggerInterface $logger = null,
    ) {
    }

    /**
     * @return array{processed: int, activated: int, alreadyInDebt: int}
     */
    public function generate(string $executedBy): array
    {
        $processed = $this->customerRepository->countActive();
        $alreadyInDebt = $this->customerRepository->countActiveWithMonthlyDebt();
        $activated = $this->customerRepository->activateMonthlyDebtForActiveWithoutDebt();

        $result = [
            'processed' => $processed,
            'activated' => $activated,
            'alreadyInDebt' => $alreadyInDebt,
        ];

        $this->logger?->info('Monthly debt generated by administrator.', [
            'executedBy' => $executedBy,
            'processed' => $processed,
            'activated' => $activated,
            'alreadyInDebt' => $alreadyInDebt,
        ]);

        return $result;
    }
}
