services:
  database:
    image: mysql:8.0
    container_name: beruki_db
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: beruki
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./docker/php
    container_name: beruki_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    tty: true

  frontend:
    build: ./docker/node
    container_name: beruki_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    command: npx ng serve --host 0.0.0.0 --poll 1000
    tty: true

  nginx:
    image: nginx:stable
    container_name: beruki_nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - frontend
      - backend

volumes:
  db_data: